name: minimark
version: 0.7.0
synopsis: Simple mark-up for HTML.
author: Galen Huntington <galen.huntington@gmail.com>
license: MIT
category: Web

default-extensions:
   - BlockArguments
   - NoImplicitPrelude
   - OverloadedStrings

source-dirs:
   - .

library: {}

executable:
   main: main.hs

dependencies:
   - base
   - base-prelude
   - bytestring
   - containers
   - megaparsec
   - mtl
   - text
   - xmlhtml
   - data-default

