name: minimark
version: 0.2.2
synopsis: Simple mark-up for HTML.
author: Galen Huntington <galen@alumni.reed.edu>
license: MIT
category: Web

default-extensions:
   - BlockArguments
   - NoImplicitPrelude
   - OverloadedStrings
ghc-options: -pgmF hpre -F

source-dirs:
   - .

library: {}

executable:
   main: main.hs

build-tools:
   hpre: 1.*

dependencies:
   base: ">= 4.9 && < 5"
   base-prelude: 1.3.*
   bytestring: 0.10.*
   containers: 0.6.*
   megaparsec: 8.*
   mtl: 2.2.*
   text: 1.2.*
   xmlhtml: 0.2.*

