name: minimark
version: 0.6.1
synopsis: Simple mark-up for HTML.
author: Galen Huntington <galen@alumni.reed.edu>
license: MIT
category: Web

default-extensions:
   - BlockArguments
   - NoImplicitPrelude
   - OverloadedStrings
ghc-options: -pgmF hpre -F

source-dirs:
   - .

library: {}

executable:
   main: main.hs

build-tools:
   - hpre

dependencies:
   - base
   - base-prelude
   - bytestring
   - containers
   - megaparsec
   - mtl
   - text
   - xmlhtml
   - data-default

